# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helptitle', models.CharField(max_length=50)),
                ('helpkeyword', models.CharField(max_length=50)),
                ('helptxt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='odlinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odltype', models.CharField(max_length=20)),
                ('odlip', models.CharField(max_length=20)),
                ('odlport', models.CharField(max_length=10)),
                ('odlkey', models.CharField(max_length=20)),
                ('odlright', models.CharField(max_length=10)),
                ('odlstate', models.CharField(max_length=10)),
                ('odllocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='odlsetlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oeoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeotype', models.CharField(max_length=20)),
                ('oeoip', models.CharField(max_length=20)),
                ('oeoport', models.CharField(max_length=10)),
                ('oeokey', models.CharField(max_length=20)),
                ('oeoright', models.CharField(max_length=10)),
                ('oeostate', models.CharField(max_length=10)),
                ('oeolocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oeosetlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
    ]
