# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oeoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeoname', models.CharField(max_length=30)),
                ('oeoip', models.CharField(max_length=20)),
                ('oeoport', models.CharField(max_length=10)),
                ('oeokey', models.CharField(max_length=20)),
                ('oeoright', models.CharField(max_length=10)),
                ('oeostate', models.CharField(max_length=10)),
                ('oeotype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='oeosetlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateField()),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
    ]
