# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oeoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeoCardBelong', models.CharField(max_length=10)),
                ('oeoCardInerId', models.CharField(max_length=10)),
                ('oeoCardLocal', models.CharField(max_length=20)),
                ('oeoCardOutPort', models.CharField(max_length=10)),
                ('oeoCardInWss', models.CharField(max_length=10)),
                ('oeoCardInWssPort', models.CharField(max_length=10)),
                ('oeoCardFrequency', models.IntegerField()),
                ('oeoCardState', models.CharField(max_length=10)),
            ],
        ),
    ]
