# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0002_oeocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='oeoCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=10)),
                ('slotid', models.CharField(max_length=10)),
                ('chanel', models.CharField(max_length=10)),
                ('statelocal', models.CharField(max_length=10)),
                ('stateremote', models.CharField(max_length=10)),
                ('take', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='oeoCardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('deviceid', models.CharField(max_length=10)),
                ('slotid', models.CharField(max_length=10)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oeoChanelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanelid', models.CharField(max_length=10)),
                ('wavelength', models.CharField(max_length=20)),
                ('oeocode', models.CharField(max_length=20)),
                ('wsscode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oeoHealthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('deviceid', models.CharField(max_length=10)),
                ('powerA', models.CharField(max_length=10)),
                ('powerB', models.CharField(max_length=10)),
                ('fan', models.CharField(max_length=10)),
                ('tempture', models.CharField(max_length=10)),
            ],
        ),
    ]
