# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_oeocardinfo_oeocardlog_oeochanelmap_oeohealthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='wssInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsstype', models.CharField(max_length=20)),
                ('wssip', models.CharField(max_length=20)),
                ('wssport', models.CharField(max_length=10)),
                ('wsskey', models.CharField(max_length=20)),
                ('wssright', models.CharField(max_length=10)),
                ('wssstate', models.CharField(max_length=10)),
                ('wsslocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='wssSetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
    ]
