# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_wssinfo_wsssetlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='wssCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=10)),
                ('chanel', models.CharField(max_length=10)),
                ('port', models.CharField(default='1', max_length=10)),
                ('att', models.CharField(default='255', max_length=10)),
                ('take', models.CharField(default='NO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='wssCardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('deviceid', models.CharField(max_length=10)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
    ]
