# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0005_wsscardinfo_wsscardlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainpagepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetype', models.CharField(max_length=20)),
                ('deviceid', models.CharField(max_length=20)),
                ('portid', models.CharField(max_length=20)),
                ('porttype', models.CharField(max_length=20)),
                ('x', models.CharField(max_length=20)),
                ('y', models.CharField(max_length=20)),
            ],
        ),
    ]
