# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0006_mainpagepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='lightPathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('startswitchid', models.CharField(max_length=10)),
                ('startswitchport', models.CharField(max_length=10)),
                ('startodoid', models.CharField(max_length=10)),
                ('startoeoslot', models.CharField(max_length=10)),
                ('awgin', models.CharField(max_length=10)),
                ('hin', models.CharField(max_length=10)),
                ('wssid', models.CharField(max_length=10)),
                ('wssport', models.CharField(max_length=10)),
                ('endoeoid', models.CharField(max_length=10)),
                ('endoeoslot', models.CharField(max_length=10)),
                ('enswitchid', models.CharField(max_length=10)),
                ('endswitchport', models.CharField(max_length=10)),
                ('att', models.CharField(max_length=10)),
                ('chanel', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
