# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0008_lightpathinfo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='lightpathlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.CharField(max_length=40)),
                ('lightpathname', models.CharField(max_length=40)),
                ('logtype', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=100)),
            ],
        ),
    ]
